FROM alpine:3.1

MAINTAINER Gergely Nemeth <gergely@risingstack.com>

RUN apk add --update \
	binutils-gold \
	curl \
	git \
	gcc \
	g++ \
	libgcc \
	libstdc++ \
	linux-headers \
	make \
	paxctl \
	python
